//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oceanware.Ocean {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oceanware.Ocean.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active rule set can not contain any pipe symbols. This is normally caused when a validation constant is passed that is for multiple rule sets and not a single rule set that this property requires..
        /// </summary>
        public static string ActiveRuleSetCanNotContainPipeSymbols {
            get {
                return ResourceManager.GetString("ActiveRuleSetCanNotContainPipeSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one password characteristic must be Yes.
        /// </summary>
        public static string AtLeastOnePasswordCharacteristicMustBeYes {
            get {
                return ResourceManager.GetString("AtLeastOnePasswordCharacteristicMustBeYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank routing number validation rule can only be applied to String properties..
        /// </summary>
        public static string BankRoutingNumberValidationRuleCanOnlyBeAppliedToStringProperties {
            get {
                return ResourceManager.GetString("BankRoutingNumberValidationRuleCanOnlyBeAppliedToStringProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean required validation rule can only be applied to Boolean or Boolean? type properties..
        /// </summary>
        public static string BooleanRequiredValidationRuleCanOnlyBeAppliedToBooleanOrNullableBooleanProperties {
            get {
                return ResourceManager.GetString("BooleanRequiredValidationRuleCanOnlyBeAppliedToBooleanOrNullableBooleanProperties" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is not a valid credit card number..
        /// </summary>
        public static string CreditCardNumberIsNotAValidCreditCardNumberFormat {
            get {
                return ResourceManager.GetString("CreditCardNumberIsNotAValidCreditCardNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is not a valid credit card number.  Only numeric input is allowed..
        /// </summary>
        public static string CreditCardNumberIsNotAValidCreditCardNumberOnlyNumericInputIsAllowedFormat {
            get {
                return ResourceManager.GetString("CreditCardNumberIsNotAValidCreditCardNumberOnlyNumericInputIsAllowedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number validation rule can only be applied to String properties..
        /// </summary>
        public static string CreditCardNumberValidationRuleCanOnlyBeAppliedToStringProperties {
            get {
                return ResourceManager.GetString("CreditCardNumberValidationRuleCanOnlyBeAppliedToStringProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}..
        /// </summary>
        public static string DateMustBeEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("DateMustBeEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string DateMustBeGreaterThanOrEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("DateMustBeGreaterThanOrEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string DateMustBeGreaterThanTargetValueFormat {
            get {
                return ResourceManager.GetString("DateMustBeGreaterThanTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string DateMustBeLessThanOrEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("DateMustBeLessThanOrEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string DateMustBeLessThanTargetValueFormat {
            get {
                return ResourceManager.GetString("DateMustBeLessThanTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not equal {1}..
        /// </summary>
        public static string DateMustNotBeEqualTargetValueFormat {
            get {
                return ResourceManager.GetString("DateMustNotBeEqualTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} did not match any of the acceptable values {2}..
        /// </summary>
        public static string DomainValidationValueDidNotMatchAnyAcceptableValueFormat {
            get {
                return ResourceManager.GetString("DomainValidationValueDidNotMatchAnyAcceptableValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLoading never called after a BeginLoading call was made. No operations are permitted until EndLoading has been called..
        /// </summary>
        public static string EndLoadingNeverCalledAfterBegingLoading {
            get {
                return ResourceManager.GetString("EndLoadingNeverCalledAfterBegingLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndLoading never called after a BeginLoading call was made. No operations are permitted until EndLoading has been called..
        /// </summary>
        public static string EndLoadingNeverCalledAfterBeginLoading {
            get {
                return ResourceManager.GetString("EndLoadingNeverCalledAfterBeginLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} for enum type name {1} was not programmed..
        /// </summary>
        public static string EnumValueNotProgrammedFormat {
            get {
                return ResourceManager.GetString("EnumValueNotProgrammedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string InRangeRuleMustBeGreaterThanFormat {
            get {
                return ResourceManager.GetString("InRangeRuleMustBeGreaterThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string InRangeRuleMustBeGreaterThanOrEqualFormat {
            get {
                return ResourceManager.GetString("InRangeRuleMustBeGreaterThanOrEqualFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string InRangeRuleMustBeLessThanFormat {
            get {
                return ResourceManager.GetString("InRangeRuleMustBeLessThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string InRangeRuleMustBeLessThanOrEqualFormat {
            get {
                return ResourceManager.GetString("InRangeRuleMustBeLessThanOrEqualFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} of enum {1} is not supported..
        /// </summary>
        public static string InvalidEnumValueExceptionMessageFormat {
            get {
                return ResourceManager.GetString("InvalidEnumValueExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} of enum {1} is not supported..
        /// </summary>
        public static string InvalidEnumValueExceptionMessageFormat1 {
            get {
                return ResourceManager.GetString("InvalidEnumValueExceptionMessageFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field..
        /// </summary>
        public static string IsARequiredFieldFormat {
            get {
                return ResourceManager.GetString("IsARequiredFieldFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is greater than maxValue.
        /// </summary>
        public static string IsGreaterThanMaxValue {
            get {
                return ResourceManager.GetString("IsGreaterThanMaxValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is longer than {1}..
        /// </summary>
        public static string IsLongerThanFormat {
            get {
                return ResourceManager.GetString("IsLongerThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must have a value..
        /// </summary>
        public static string KeyMustHaveAValue {
            get {
                return ResourceManager.GetString("KeyMustHaveAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length must be greater than zero..
        /// </summary>
        public static string MaximumLengthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MaximumLengthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minimum length is {1}..
        /// </summary>
        public static string MinimumLengthIsFormat {
            get {
                return ResourceManager.GetString("MinimumLengthIsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length must be less than or equal to the maximum length..
        /// </summary>
        public static string MinimumLengthMustBeLessThanOrEqualToMaximumLength {
            get {
                return ResourceManager.GetString("MinimumLengthMustBeLessThanOrEqualToMaximumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple of validator requires it be applied to an integer property..
        /// </summary>
        public static string MultipleOfValidatorRequirsItBeAppliedToAnIntegerProperty {
            get {
                return ResourceManager.GetString("MultipleOfValidatorRequirsItBeAppliedToAnIntegerProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string MustBeEqualToOrGreaterThanFormat {
            get {
                return ResourceManager.GetString("MustBeEqualToOrGreaterThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string MustBeEqualToOrLessThanFormat {
            get {
                return ResourceManager.GetString("MustBeEqualToOrLessThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string MustBeGreaterThanFormat {
            get {
                return ResourceManager.GetString("MustBeGreaterThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than or equal to Minimum Length..
        /// </summary>
        public static string MustBeGreaterThanOrEqualToMinimumLength {
            get {
                return ResourceManager.GetString("MustBeGreaterThanOrEqualToMinimumLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than zero..
        /// </summary>
        public static string MustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string MustBeLessThanFormat {
            get {
                return ResourceManager.GetString("MustBeLessThanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is DBNull but is required to be non-null..
        /// </summary>
        public static string NotNullIsDBNullFormat {
            get {
                return ResourceManager.GetString("NotNullIsDBNullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null but is required to be non-null..
        /// </summary>
        public static string NotNullIsNullFormat {
            get {
                return ResourceManager.GetString("NotNullIsNullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} null value is not allowed..
        /// </summary>
        public static string NullValueIsNotAllowedFormat {
            get {
                return ResourceManager.GetString("NullValueIsNotAllowedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter must not be null..
        /// </summary>
        public static string ParameterMustNotBeNull {
            get {
                return ResourceManager.GetString("ParameterMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one digit character, .
        /// </summary>
        public static string PasswordAtLeaseOneDigitCharacter {
            get {
                return ResourceManager.GetString("PasswordAtLeaseOneDigitCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one lower case character, .
        /// </summary>
        public static string PasswordAtLeaseOneLowerCaseCharacter {
            get {
                return ResourceManager.GetString("PasswordAtLeaseOneLowerCaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one of these special characters {0}.
        /// </summary>
        public static string PasswordAtLeaseOneSpecialCharacterFormat {
            get {
                return ResourceManager.GetString("PasswordAtLeaseOneSpecialCharacterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least one upper case character, .
        /// </summary>
        public static string PasswordAtLeaseOneUpperCaseCharacter {
            get {
                return ResourceManager.GetString("PasswordAtLeaseOneUpperCaseCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is longer than {0}, .
        /// </summary>
        public static string PasswordMaximumLengthIsFormat {
            get {
                return ResourceManager.GetString("PasswordMaximumLengthIsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum length is {0}, .
        /// </summary>
        public static string PasswordMinimumLengthIsFormat {
            get {
                return ResourceManager.GetString("PasswordMinimumLengthIsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}..
        /// </summary>
        public static string PropertyMustBeEqualToOtherPropertyFormat {
            get {
                return ResourceManager.GetString("PropertyMustBeEqualToOtherPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string PropertyMustBeGreaterThanOrEqualToOtherPropertyFormat {
            get {
                return ResourceManager.GetString("PropertyMustBeGreaterThanOrEqualToOtherPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string PropertyMustBeGreaterThanOtherPropertyFormat {
            get {
                return ResourceManager.GetString("PropertyMustBeGreaterThanOtherPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string PropertyMustBeLessThanOrEqualToOtherPropertyFormat {
            get {
                return ResourceManager.GetString("PropertyMustBeLessThanOrEqualToOtherPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string PropertyMustBeLessThanOtherPropertyFormat {
            get {
                return ResourceManager.GetString("PropertyMustBeLessThanOtherPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not equal {1}..
        /// </summary>
        public static string PropertyMustNotBeEqualToOtherPropertyFormat {
            get {
                return ResourceManager.GetString("PropertyMustNotBeEqualToOtherPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required email pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredEmailPatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredEmailPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required IP address pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredIPAddressPatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredIPAddressPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required {1} pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredPatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required SSN pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredSSNPatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredSSNPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required URL pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredURLPatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredURLPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required US phone number pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredUSPhoneNumberPatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredUSPhoneNumberPatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not match the required zip code pattern..
        /// </summary>
        public static string RegularExpressionDidNotMatchTheRequiredZipCodePatternFormat {
            get {
                return ResourceManager.GetString("RegularExpressionDidNotMatchTheRequiredZipCodePatternFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid custom regular expression pattern..
        /// </summary>
        public static string RegularExpressionInvalidCustomRegularExpressionPattern {
            get {
                return ResourceManager.GetString("RegularExpressionInvalidCustomRegularExpressionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; state abbreviation is not valid..
        /// </summary>
        public static string StateAbbreviationIsNotValidFormat {
            get {
                return ResourceManager.GetString("StateAbbreviationIsNotValidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is null, empty, or white space..
        /// </summary>
        public static string StringIsNullEmptyOrWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("StringIsNullEmptyOrWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The encrypted text must have a value..
        /// </summary>
        public static string TheEncryptedTextMustHaveAValue {
            get {
                return ResourceManager.GetString("TheEncryptedTextMustHaveAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text must have valid value..
        /// </summary>
        public static string TheTextMustHaveAValue {
            get {
                return ResourceManager.GetString("TheTextMustHaveAValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create AES crypto object..
        /// </summary>
        public static string UnableToCreateAESCryptoObject {
            get {
                return ResourceManager.GetString("UnableToCreateAESCryptoObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation attribute resource property {0} is not a string type, instead is {1}..
        /// </summary>
        public static string ValidationAttributeResourcePropertyNotStringTypeFormat {
            get {
                return ResourceManager.GetString("ValidationAttributeResourcePropertyNotStringTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is not a valid bank routing number. All bank routing numbers are 9 digits in length..
        /// </summary>
        public static string ValueIsNotAValidBankRoutingNumberAllBankRoutingNumbersAreNineDigitsInLengthFormat {
            get {
                return ResourceManager.GetString("ValueIsNotAValidBankRoutingNumberAllBankRoutingNumbersAreNineDigitsInLengthFormat" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is not a valid bank routing number. Only numeric input is allowed..
        /// </summary>
        public static string ValueIsNotAValidBankRoutingNumberAllBankRoutingNumbersCharactersMustBeNumericFormat {
            get {
                return ResourceManager.GetString("ValueIsNotAValidBankRoutingNumberAllBankRoutingNumbersCharactersMustBeNumericForm" +
                        "at", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is not a valid bank routing number. The first digit must be a 0 or a 1..
        /// </summary>
        public static string ValueIsNotAValidBankRoutingNumberAllBankRoutingNumbersFirstDigitMustBeZeorOrOneFormat {
            get {
                return ResourceManager.GetString("ValueIsNotAValidBankRoutingNumberAllBankRoutingNumbersFirstDigitMustBeZeorOrOneFo" +
                        "rmat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} is not a valid bank routing number..
        /// </summary>
        public static string ValueIsNotAValidBankRoutingNumberFormat {
            get {
                return ResourceManager.GetString("ValueIsNotAValidBankRoutingNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value {1} is not divisible by {2}..
        /// </summary>
        public static string ValueIsNotDivisibleByFormat {
            get {
                return ResourceManager.GetString("ValueIsNotDivisibleByFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null, empty, or white space..
        /// </summary>
        public static string ValueIsNullEmptyOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValueIsNullEmptyOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be equal to {1}..
        /// </summary>
        public static string ValueMustBeEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("ValueMustBeEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than DateTime.MinValue..
        /// </summary>
        public static string ValueMustBeGreaterThanDateTimeMinDateFormat {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanDateTimeMinDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than one..
        /// </summary>
        public static string ValueMustBeGreaterThanOne {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equal to {1}..
        /// </summary>
        public static string ValueMustBeGreaterThanOrEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanOrEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}..
        /// </summary>
        public static string ValueMustBeGreaterThanTargetValueFormat {
            get {
                return ResourceManager.GetString("ValueMustBeGreaterThanTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than or equal to {1}..
        /// </summary>
        public static string ValueMustBeLessThanOrEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("ValueMustBeLessThanOrEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than {1}..
        /// </summary>
        public static string ValueMustBeLessThanTargetValueFormat {
            get {
                return ResourceManager.GetString("ValueMustBeLessThanTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must not equal {1}..
        /// </summary>
        public static string ValueMustNotBeEqualToTargetValueFormat {
            get {
                return ResourceManager.GetString("ValueMustNotBeEqualToTargetValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was null..
        /// </summary>
        public static string ValueWasNullFormat {
            get {
                return ResourceManager.GetString("ValueWasNullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was null or DBNull but was required..
        /// </summary>
        public static string ValueWasNullOrDBNullButWasRequired {
            get {
                return ResourceManager.GetString("ValueWasNullOrDBNullButWasRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value was null, DBNull, or empty string but was required..
        /// </summary>
        public static string ValueWasNullOrDBNullOrEmptyStringButWasRequired {
            get {
                return ResourceManager.GetString("ValueWasNullOrDBNullOrEmptyStringButWasRequired", resourceCulture);
            }
        }
    }
}
